version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ~/rutt/identity/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "identity"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "2080:8080"
