server:
  servlet:
    context-path: /tests/api
  port: 8080
spring:
  datasource:
    username: postgres
    password: 0
    url: jdbc:postgresql://localhost:5432/data
  jpa:
    hibernate:
      ddl-auto: create
